import mongoose from "mongoose";

const userSchema= new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    userName:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
     password:{
        type:String,
        required:true        
    },
    profileImage:{
        type:String
    },
    followers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
        }
    ],
    following:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
        }
    ],
    posts:[
         {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Post"
        }
    ],
    saved:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Post" 
        }
    ],
    loop:[
         {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Loop" 
        }
    ],
    story:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Story" 
    },
    resetOtp:{
        type:String
    },
    otpExpires:{
        type:Number  // Changed from Date to Number
    },
    isOtpVerified:{
        type:Boolean,
        default:false  // Changed from true to false
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    verificationStatus:{
        type:String,
        enum:["pending","approved","rejected"],
        default:"pending"
    },
    role:{
        type:String,
        enum:["user","admin"],
        default:"user"
    },
    verifiedAt:{
        type:Date
    },
    verifiedBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }
},{timestamps:true})

const User = mongoose.model("User",userSchema)
export default User
